apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sample-app
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: in-cluster
            url: https://kubernetes.default.svc
            overlay: management
          - cluster: workload-cluster
            url: https://192.168.58.2:8443
            overlay: workload
  template:
    metadata:
      name: 'sample-app-{{cluster}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/sharanch/k8s-platform-fleet
        targetRevision: HEAD
        path: 'apps/sample-app/overlays/{{overlay}}'
      destination:
        server: '{{url}}'
        namespace: sample-app
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
